name: test
on: 
  push:

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    env:
        NPM_CONFIG_LOGLEVEL: verbose
    steps:
    # - run: ls -la /usr/lib/node_modules
    - uses: actions/checkout@v4
    # - uses: ./.github/actions/test
    #   with:
    #     test: test
    # # - run: tldr tar
    # # - run: ls -la /usr/lib/node_modules
    # - run: which tldr
    - run: env | sort
    - run: cat ~/.bashrc
    - run: echo "$PATH"
    - run: which npm
    - uses: devcontainers/ci@v0.3
      with:
        imageName: node
        runCmd: |
            ls -la /usr/lib/node_modules