name: test
on: 
  push:

jobs:
  build:
    name: test
    runs-on: node20
    steps:
    # - run: ls -la /usr/lib/node_modules
    - uses: actions/checkout@v4
    - uses: ./.github/actions/test
      with:
        test: test
    - run: ls -la /usr/lib/node_modules
